import AllCurrencies from '@/components/AllCurrencies/AllCurrencies';
import DropDown from '@/components/DropDown/DropDown';
import CurrencySelect from '@/components/ui/CurrencySelect/CurrencySelect';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Currency-app: Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        {/* <DropDown /> */}
        <CurrencySelect />
        <AllCurrencies />
      </div>
    </>
  );
}
